// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-06-11 05:55
// Generated by: GTS-DEV\Pranolo
//-------------------------------------------------------
namespace RgenLib.Templates
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using EnvDTE80;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.6.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="DbSet", Description="DbSet", HideInDialog=false)]
    public partial class DbSet : Kodeo.Reegenerator.Generators.CodeRenderer
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="output">The instance where the rendered code will be written to.</param>
        ///<param name="candidates"></param>
        public virtual void GenDbset(System.IO.StringWriter output, IEnumerable<DbsetCandidate> candidates)
        {
 foreach(var c in candidates){
            output.Write("\r\npublic DbSet<");
            output.Write( c.Class.FullName );
            output.Write("> ");
            output.Write(c.SetName );
            output.Write("{get;set;}\r\n");
 }
            output.WriteLine();
        }
    }
}
